### ISSUE TITLE
[ChatLLaMA] Training process halted

### ISSUE THREAD

**Issue by MuffinC** [nebuly-ai/nebullvm#309]
![image](https://user-images.githubusercontent.com/56317821/228220945-c73ad45f-e57a-4ace-98b3-8edabc636bb2.png)

Hi, it seemed like the training process was fine unitl it hit iteration 71? ran the line: python artifacts/main.py artifacts/config/config.yaml --type ALL

**Comment by PierpaoloSorbellini** [comment]
Hi @MuffinC, thanks for reaching out, we are sorry for the inconvenience. 
This problem should have been fixed in the previous release and we haven't encountered it since. 
Did you use the last available version of the pip or of the source code?

**Comment by MuffinC** [comment]
![image](https://user-images.githubusercontent.com/56317821/229426842-ae4cb0c2-e832-460e-8021-1ecba645863e.png)
Hi Pier, yes i am using the latest version of pip and i've just pulled from the repo while changing my python version to 10. Still encountering the error
